In [1]:
from sklearn.preprocessing import MinMaxScaler
import itertools
import pandas as pd
import torch

# get our predefined functions (for data processing, etc.)
import QCircNet.utils as ut

# get our predefined quantum circuits and neural networks
import QCircNet.circuits.CustomCircuits as cn
import QCircNet.QuantumNN as qnn
import QCircNet.BinaryQuantumNN as bqnn

In [2]:
import torch
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Set random seed for reproducibility
np.random.seed(42)

# Generate X with shape (100, 16) - random float values
X = np.random.rand(100, 16).astype(np.float32)  # Ensure it's float32 for PyTorch

# Generate y labels (100 samples, 10 possible classes)
y_labels = np.random.randint(0, 10, size=(100, 1))

# One-hot encode y
encoder = OneHotEncoder(sparse_output=False, categories=[np.arange(10)])
y = encoder.fit_transform(y_labels).astype(np.float32)  # Ensure it's float32

# Convert to PyTorch tensors
X_tensor = torch.tensor(X)
y_tensor = torch.tensor(y)

# Print shapes to confirm
print("X_tensor shape:", X_tensor.shape)  # (100, 16)
print("y_tensor shape:", y_tensor.shape)  # (100, 10)

# Optional: Show first few rows
print("First 5 labels:\n", y_tensor[:5])



X_tensor shape: torch.Size([100, 16])
y_tensor shape: torch.Size([100, 10])
First 5 labels:
 tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])


In [3]:
N_QUBITS = 4
FEAT_PER_QUBIT = 4
seed = 42
circuit = cn.DoubleEntanglementVLCircuit

In [4]:
model = qnn.QuantumClassifierMNIST(n_qubits=N_QUBITS, features_per_qubit=FEAT_PER_QUBIT, circuit=circuit, seed=seed)

# model = bqnn.BinQuantumNeuralNetwork(n_qubits=N_QUBITS, features_per_qubit=FEAT_PER_QUBIT, circuit=circuit, seed=seed)

In [5]:
X_tensor.shape

torch.Size([100, 16])

In [6]:
prop, logit = model(X_tensor)

In [7]:
prop.shape

torch.Size([100, 10])

In [8]:
prop

tensor([[0.0684, 0.0430, 0.0425, 0.0815, 0.0571, 0.2045, 0.1783, 0.1370, 0.0994,
         0.0884],
        [0.0710, 0.0449, 0.0450, 0.0804, 0.0544, 0.2073, 0.1844, 0.1291, 0.0982,
         0.0853],
        [0.0623, 0.0384, 0.0370, 0.0837, 0.0637, 0.1968, 0.1639, 0.1567, 0.1020,
         0.0956],
        [0.0735, 0.0469, 0.0475, 0.0792, 0.0519, 0.2098, 0.1901, 0.1220, 0.0968,
         0.0824],
        [0.0977, 0.0670, 0.0760, 0.0647, 0.0303, 0.2226, 0.2431, 0.0646, 0.0794,
         0.0547],
        [0.0682, 0.0428, 0.0423, 0.0816, 0.0573, 0.2042, 0.1778, 0.1376, 0.0995,
         0.0886],
        [0.0656, 0.0409, 0.0400, 0.0825, 0.0600, 0.2012, 0.1718, 0.1457, 0.1007,
         0.0916],
        [0.0678, 0.0425, 0.0420, 0.0817, 0.0577, 0.2038, 0.1769, 0.1388, 0.0997,
         0.0891],
        [0.0681, 0.0427, 0.0422, 0.0816, 0.0574, 0.2041, 0.1776, 0.1380, 0.0996,
         0.0887],
        [0.0674, 0.0422, 0.0416, 0.0819, 0.0581, 0.2033, 0.1760, 0.1401, 0.0999,
         0.0895],
        [0

In [9]:
y_pred_class = torch.argmax(prop, dim=1)
y_pred_class

tensor([5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5])

In [10]:
model.evaluate(X_tensor, y_tensor)

(2.2950186729431152, 0.15, 0.02448979591836735, 0.15, 0.042105263157894736)